### ISSUE TITLE
Class name

### ISSUE THREAD

**Issue by tapochek666** [littletijn/spooky-view#16]
Greetings. How do I find out the Class name? I add some .exes, but there is no transparency.

**Comment by littletijn** [comment]
Hello! The class name is not required to make a app transparent. When a app is added to the list, a option [All other windows] will be available in the Windows list. When you set the transparency on that option, it will apply the transparency on all the windows of the app selected in the Apps list.

If you need a specific window, click the Add... button when the window is visible. In the "Add window" screen, all visible windows should be listed with their class name.

It looks like the app you want to make transparent isn't supported by Spooky View. Some apps (like WPF based apps) cannot be set transparent.

Can you name the app you want to make transparent?

**Comment by tapochek666** [comment]
Sorry for taking a long time to respond. It was not possible to make programs such as Revo Uninstaller Pro, Your Uninstaller transparent! and most importantly, the standard Windows 11 task manager.

**Comment by littletijn** [comment]
Try running Spooky View with higher privileges by running it as administrator. To do this, right click the app icon of Spooky View in the start menu and click on Run as administrator.

Because Task Manager and the other apps run as administrator, Spooky View cannot modify them unless it runs at the same integrity level.

**Comment by tapochek666** [comment]
Thank you very much. How did I not think of running the program as an administrator?! Now everything works (the above programs are now also transparent)!

**Comment by littletijn** [comment]
Thans for your response! And great to hear that the app is working correctly now for you. :)

I will close this issue and update the FAQ.
